# Generated by Django 4.1.7 on 2023-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slicice',
            name='slika',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
