# Generated by Django 4.1.7 on 2023-03-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_slicice_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slicice',
            name='slika',
            field=models.ImageField(upload_to='slicice'),
        ),
    ]
