# Generated by Django 4.1.7 on 2023-04-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_slicice_slika'),
    ]

    operations = [
        migrations.AddField(
            model_name='slicice',
            name='url',
            field=models.CharField(default='/airpolution', max_length=30),
            preserve_default=False,
        ),
    ]
